config/routes.rb
DplaPortal::Application.routes.draw do
  resources :apps


  devise_for :users, controllers: {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions      => "sessions",
    :passwords     => "passwords"
  }

  get '/item/:id', to: 'items#show', as: 'item', format: 'html'
  get '/item/:id.json', to: 'items#show', as: 'item_json', format: 'json'
  post '/items/next'
  post '/items/previous'

  resources :subjects, only: :index
  resources :partners, only: :index

  scope only: :show do
    resource :search,    controller: :search
    resource :timeline,  controller: :timeline
    resource :map,       controller: :map
    resource :bookshelf, controller: :bookshelf
  end

  scope '/saved' do
    resources :saved_searches, path: 'searches', only: [:index, :create, :destroy] do
      post 'destroy_bulk', on: :collection
    end
    resources :saved_lists, path: 'lists', id: /\d+/ do
      get 'unlisted', action: :show, on: :collection
    end
    scope '/lists' do
      post   'add_item',              to: 'saved_lists#add_item',          as: :add_saved_item
      delete 'delete_item',           to: 'saved_lists#delete_item',       as: :delete_saved_item
      delete 'delete_positions',      to: 'saved_lists#delete_positions',  as: :delete_positions
      post   'reorder_positions',     to: 'saved_lists#reorder_positions', as: :reorder_positions
      post   'copy_positions',        to: 'saved_lists#copy_positions',    as: :copy_positions
      post   'move_positions',        to: 'saved_lists#move_positions',    as: :move_positions
      post   'switch_status',         to: 'saved_lists#switch_status',     as: :switch_list_status
    end
  end

  match '/welcome' => 'users#welcome'
  root to: 'pages#home'

  # Redner 404 error page for uncatched routes
  match '*a', :to => 'application#render_404', format: false
end

app/views/shared/_aside_toggle.html.haml
- if @search.count > 0
  .toggle.mobile.Marticle
    Refine search
    %span.icon-arrow-thin-right{"aria-hidden" => "true"}
  .toggle.mobile.Maside
    Refine search
    %span.icon-arrow-thin-right{"aria-hidden" => "true"}

app/views/shared/_flash_message.html.haml
- unless flash[:notice].blank?
  %div{ :class => "flash flash-notice" }= flash[:notice]
- unless flash[:error].blank?
  %div{ :class => "flash flash-error" }= flash[:error]
- unless flash[:alert].blank?
  %div{ :class => "flash flash-alert" }= flash[:alert]

app/views/shared/_footer_navigation.html.haml
= semantic_navigation config: :bootstrap do |n|
  - n.item 'Home', root_path
  - n.item 'Map', map_path, highlights_on: [{controller: 'map'}]
  - n.item 'Timeline', timeline_path, highlights_on: [{controller: 'timeline'}]
  - n.item 'Partners', partners_path
  - n.item 'Subjects', subjects_path

app/views/shared/_main_navigation.html.haml
= semantic_navigation config: :bootstrap do |n|
  - n.item 'Home', root_path
  - n.item 'Map', map_path, highlights_on: [{controller: 'map'}]
  - n.item 'Timeline', timeline_path, highlights_on: [{controller: 'timeline'}]
  - n.item 'Apps', apps_path
%ul.nav-signup
  - if user_signed_in?
    %li.welcome
      = link_to edit_user_registration_path do
        Welcome,
        = current_user.name
  - else
    %li.login.bg
      = link_to 'Login', new_user_session_path, class: 'login cBoxElement'

app/views/shared/_refine_control.html.haml
.controls
  .toggle
    %span.icon-arrow-thin-left{"aria-hidden" => "true"}
    Hide
  .toggle.mobile.Marticle
    Refine search
    %span.icon-arrow-thin-right{"aria-hidden" => "true"}

app/views/shared/_search_block.html.haml
%section.searchRow
  .searchRowLeft
  .searchRowRight
    .searchViews
      %span View:
      %ul
        %li.active
          = link_to search_items_path(params.except(:controller, :action)) do
            %span.icon-view-list{"aria-hidden" => "true"}
        %li
          %a.viewTwo{:href => ""}
            %span.icon-view-map{"aria-hidden" => "true"}
        %li
          = link_to timeline_path(params.except(:controller, :action)), class: 'viewThree' do
            %span.icon-view-time{"aria-hidden" => "true"}
    %a.search-btn{:href => ""} Search
    = form_tag('', method: :get, authenticity_token: false, id: :searchBox) do
      = preserved_search_fields without: :q
      = text_field_tag :q, params[:q], placeholder: 'Search the Library'
      = submit_tag 'Search', class: 'searchBtn', name: nil

app/views/shared/_search_panel.html.haml
%section.searchRow
  .searchRowLeft
    - if params[:back_uri].present?
      = link_to "« back to search results", params[:back_uri]
  .searchRowRight
    - if %w(timeline search map).include? params[:controller]
      .searchViews
        %ul
          %li{class: params[:controller] == 'search' && 'active'}
            = link_to search_path(params.except(:controller, :action)) do
              %span.icon-view-list{"aria-hidden" => "true", :title => "List"}
              %span.icon-label List
          %li{class: params[:controller] == 'map' && 'active'}
            = link_to map_path(params.except(:controller, :action)), class: 'viewTwo' do
              %span.icon-view-map{"aria-hidden" => "true", :title => "Map"}
              %span.icon-label Map
          %li{class: params[:controller] == 'timeline' && 'active'}
            = link_to timeline_path(params.except(:controller, :action)), class: 'viewThree' do
              %span.icon-view-time{"aria-hidden" => "true", :title => "Timeline"}
              %span.icon-label Timeline
    %a.search-btn{:href => ""}
      %span.icon-mag-glass{"aria-hidden" => "true"}
      %span.visuallyhidden Search
    - url = %w(timeline search map).include?(params[:controller]) ? params[:controller] : '/search'
    - Rails.logger.debug "URL: #{url}"
    = form_tag(url, method: :get, authenticity_token: false, id: :searchBox, class: 'search-form', role: 'search') do
      = preserved_search_fields without: :q
      = label_tag 'searchField', 'Search the Library', :class => 'visuallyhidden'
      = text_field_tag :searchField, params[:q], placeholder: 'Search the Library', name: "q"
      = submit_tag 'Search', class: 'searchBtn', name: nil

app/views/shared/_share_save.html.haml
%ul.shareSave
  - if 'items' == params[:controller]
    - if @previous.present?
      %li.btn
        = link_to '« Previous', items_previous_path(position: @previous, back_uri: params[:back_uri]), method: :post
    - if @next.present?
      %li.btn
        = link_to 'Next »', items_next_path(position: @next, back_uri: params[:back_uri]), method: :post
  %li.btn
    - if 'search' == params[:controller]
      = link_to "Save", saved_searches_path(params.except(:controller, :action)), method: :post
    - elsif 'items' == params[:controller]
      %a Save To...
      %ul
        %li
          - if @show_unlisted
            = link_to 'Your Saved Items', add_saved_item_path(item_id: params[:id]), method: :post
          - elsif !@lists.present?
            .sharebtn Item was already saved
        - if @lists.present?
          - @lists.each do |list|
            %li
              - item_params = {id: list, item_id: params[:id]}
              = link_to list.title, add_saved_item_path(item_params), method: :post
  %li.btn.share
    %a{:href => ""} Share
    %ul
      %li
        .sharebtn
          #fb-root
          .fb-like{"data-layout" => "button_count", "data-send" => "false", "data-show-faces" => "false", "data-width" => "450"}
      %li
        .sharebtn
          %a.twitter-share-button{:href => "https://twitter.com/share"} Tweet
          :javascript
            !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
      %li
        .sharebtn
          .g-plusone{"data-size" => "medium"}

app/views/shared/_sidebar.html.haml
%aside
  %h5 Refine search
  = render 'shared/sidebar/refine_by_subject'
  = render 'shared/sidebar/refine_by_location'
  = render 'shared/sidebar/refine_by_language'
  = render 'shared/sidebar/refine_by_provider'
  = render 'shared/sidebar/refine_by_partner'
  = render 'shared/sidebar/refine_by_type'
  - unless params[:controller] == 'timeline'
    = render 'shared/sidebar/refine_by_date'

app/views/shared/_social_icons.html.haml
- icons = Settings.widgets.social_icons
%ul.social.icons{id: defined?(block_id) ? block_id : 'social'}
  %li.facebook
    %a{href: icons.facebook}
      %span.icon-facebook{"aria-hidden" => "true"}
      %span.visuallyhidden Facebook
  %li.twitter
    %a{href: icons.twitter}
      %span.icon-twitter{"aria-hidden" => "true"}
      %span.visuallyhidden Twitter
  %li.RSS
    %a{href: icons.rss}
      %span.icon-rss{"aria-hidden" => "true"}
      %span.visuallyhidden RSS
  %li.tumblr
    %a{href: icons.tumblr}
      %span.icon-tumblr{"aria-hidden" => "true"}
      %span.visuallyhidden Tumblr

app/views/shared/_top_navigation.html.haml
%ul
  %li.aboutMenu
    = link_to wordpress_path '/' do
      About
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "Staff", wordpress_path('/about/staff/')
      %li= link_to "Board", wordpress_path('/about/board/')
      %li= link_to "Funding", wordpress_path('/about/funding/')
      %li= link_to "History", wordpress_path('/about/history/')
      %li= link_to "Policies", wordpress_path('/about/policies/')
      %li= link_to "Projects", wordpress_path('/about/projects/')
      %li= link_to "Awards", wordpress_path('/about/awards/')

  %li.aboutMenu
    = link_to wordpress_path '/hubs/' do
      Hubs
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "Become a Hub", wordpress_path('/hubs/become-a-hub/')

  %li.aboutMenu
    = link_to wordpress_path '/developers/' do
      For Developers
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "API Codex", wordpress_path('/developers/codex/')
      %li= link_to "Ideas & Projects", wordpress_path('/developers/ideas-and-projects/')
      %li= link_to "Bulk Download", wordpress_path('/developers/download/')
      %li= link_to "Sample Code & Libraries", wordpress_path('/developers/sample-code-and-libraries')
      %li= link_to "Metadata Application Profile", wordpress_path('/developers/map')
      %li= link_to "Technical Documentation", '//digitalpubliclibraryofamerica.atlassian.net/wiki/display/TECH/DPLA+Technology+Team'

  %li.aboutMenu
    = link_to wordpress_path '/education/' do
      Education
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "Primary Source Sets", '/primary-source-sets'
      %li= link_to "Education Advisory Committee", wordpress_path('/education/education-advisory-committee/')
      %li= link_to "National History Day", wordpress_path('/education/national-history-day/')
      %li= link_to "Education Collaborations", wordpress_path('/education/education-collaborations/')
      %li= link_to "Outreach Materials", wordpress_path('/education/education-promotion/')

  %li.aboutMenu
    = link_to wordpress_path '/get-involved/' do
      Get Involved
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "Community Reps", wordpress_path('/get-involved/reps/')
      %li= link_to "Ebooks", wordpress_path('/get-involved/dpla-ebooks/')
      %li= link_to "GIF IT UP", wordpress_path('/gif-it-up/')
      %li= link_to "Groups", wordpress_path('/get-involved/groups/')
      %li= link_to "Workshops", wordpress_path('/get-involved/workshops/')
      %li= link_to "DPLAfest", wordpress_path('/get-involved/dplafest/')
      %li= link_to "Follow Us", wordpress_path('/get-involved/follow/')

  %li.aboutMenu
    = link_to wordpress_path '/help/' do
      Help
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "FAQ", wordpress_path('/help/faq/')
      %li= link_to "Searching DPLA", wordpress_path('/help/search/')
      %li= link_to "Family Research", wordpress_path('/help/family-research-at-dpla/')

  %li.aboutMenu
    = link_to wordpress_path '/news/' do
      News
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "Press", wordpress_path('/news/press/')

  %li.aboutMenu
    = link_to wordpress_path '/contact/' do
      Contact
      %span.icon-arrow-thin-down{"aria-hidden" => "true"}
    %ul
      %li= link_to "Jobs", wordpress_path('/contact/jobs/')

  %li.hilight
    = link_to 'Donate', wordpress_path('/donate/')
  - if user_signed_in?
    %li.welcome
      = link_to edit_user_registration_path do
        Welcome,
        = current_user.name
    %li.signOut.bg.last= link_to "Sign out", destroy_user_session_path
  - else
    %li.login.bg
      = link_to 'Login', new_user_session_path, class: 'login cBoxElement'
    %li.signUp.bg.last
      = link_to 'Sign Up', new_user_registration_path, class: 'signUp cBoxElement'

app/views/shared/_twitter_widget.html.haml
- if  (twitter_name = Settings.widgets.twitter_username) && (twitter_widget_name = Settings.widgets.twitter_widget_id)
  :javascript                                                                             
    ! function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0],
            p = /^http:/.test(d.location) ? 'http' : 'https';
        if (!d.getElementById(id)) {
            js = d.createElement(s);
            js.id = id;
            js.src = p + "://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);
        }
    }(document, "script", "twitter-wjs");
  .twitter
    %h2.border
      = link_to "@#{twitter_name} on Twitter", "https://twitter.com/#{twitter_name}"
    %a.twitter-timeline{:href => "https://twitter.com/#{twitter_name}",
                        :data => {:widget_id => "#{Settings.widgets.twitter_widget_id}", 
                                  :link_color=> "#4691b9", 
                                  :theme => "light", 
                                  :chrome => "nofooter noheader noborders", 
                                  :tweet_limit => 2}} 

app/views/shared/_wp_news_widget.html.haml
- if wordpress_url = wordpress_path
  :javascript
    window.wordpress_url = "#{ wordpress_url }";
  #wp_news_feed
    .news
      %ul
      - if all_news_link = wordpress_path('/news/')
        =link_to 'All News »', all_news_link