config/routes.rb
DplaPortal::Application.routes.draw do
  resources :apps


  devise_for :users, controllers: {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions      => "sessions",
    :passwords     => "passwords"
  }

  get '/item/:id', to: 'items#show', as: 'item', format: 'html'
  get '/item/:id.json', to: 'items#show', as: 'item_json', format: 'json'
  post '/items/next'
  post '/items/previous'

  resources :subjects, only: :index
  resources :partners, only: :index

  scope only: :show do
    resource :search,    controller: :search
    resource :timeline,  controller: :timeline
    resource :map,       controller: :map
    resource :bookshelf, controller: :bookshelf
  end

  scope '/saved' do
    resources :saved_searches, path: 'searches', only: [:index, :create, :destroy] do
      post 'destroy_bulk', on: :collection
    end
    resources :saved_lists, path: 'lists', id: /\d+/ do
      get 'unlisted', action: :show, on: :collection
    end
    scope '/lists' do
      post   'add_item',              to: 'saved_lists#add_item',          as: :add_saved_item
      delete 'delete_item',           to: 'saved_lists#delete_item',       as: :delete_saved_item
      delete 'delete_positions',      to: 'saved_lists#delete_positions',  as: :delete_positions
      post   'reorder_positions',     to: 'saved_lists#reorder_positions', as: :reorder_positions
      post   'copy_positions',        to: 'saved_lists#copy_positions',    as: :copy_positions
      post   'move_positions',        to: 'saved_lists#move_positions',    as: :move_positions
      post   'switch_status',         to: 'saved_lists#switch_status',     as: :switch_list_status
    end
  end

  match '/welcome' => 'users#welcome'
  root to: 'pages#home'

  # Redner 404 error page for uncatched routes
  match '*a', :to => 'application#render_404', format: false
end

app/views/apps/_form.html.haml
= simple_form_for @app do |f|
  = f.input :icon
  = f.input :screenshot
  = f.input :title, required: true, autofocus: true
  = f.input :author, required: true
  = f.input :teaser_description, input_html: { rows: 5 }
  = f.input :description, input_html: { rows: 5 }
  .is_promo
    = f.input :is_promo, label: 'Show on home page'
  = f.input :home_page_url
  = f.input :develop_app_url
  .created_at
    = f.input :created_at
  %br
  = f.button :submit, class: :btn

app/views/apps/edit.html.haml
- page_title! t('.title', name: @app.title )

.layout.fullWidth
  = render 'shared/search_panel'

  %article#content{role: "main"}
    %h1 Edit app "#{@app.title_was}"
    .profile
      .tab-content
        .account
          = render 'form'

app/views/apps/index.html.haml
- set_meta_tags :og => {:description => "The DPLA's platform and open data can be used by software developers, researchers, and others to create novel environments for learning, tools for discovery, and engaging apps."}

.layout.fullWidth.app
  = render 'shared/search_panel'
  %article#content{role: "main"}
    = render 'shared/share_save'
    %h1.border App Library
    %h4 The DPLA is a platform that enables new and transformative uses of our digitized cultural heritage. The DPLA's application programming interface (API) and open data can be used by software developers, researchers, and others to create novel environments for learning, tools for discovery, and engaging apps.

    - if is_admin?
      = link_to 'Add New App', new_app_path, class: :btn
    = link_to 'Become an App Developer', wordpress_path('/developers/'), class: :btn
    .pagination= paginate @apps

    = render partial: 'shared/apps/apps_view'

    .pagination= paginate @apps

app/views/apps/new.html.haml
.layout.fullWidth
  = render 'shared/search_panel'

  %article#content{role: "main"}
    %h1 New app
    .profile
      .tab-content
        .account
          = render 'form'

app/views/apps/show.html.haml
- page_title! t('.title', name: @app.title )
- set_meta_tags :og => {:description => @app.teaser_description, :image => @app.icon}

.layout.fullWidth.app
  = render 'shared/search_panel'
  .breadCrumbs
    %ul
      %li= link_to 'App Library', apps_path
      %li= @app.title
  = render 'shared/share_save'
  %article#content.app-detail{role: "main"}
    %p.author= @app.author
    %h1= @app.title
    - if @app.screenshot.present?
      .leftSide
        = image_tag @app.screenshot
    .rightSide
      %p= @app.description
      %ul.buttons
        - if @app.home_page_url.present?
          %li.btn= link_to 'App Home page', @app.home_page_url
        - if @app.develop_app_url.present?
          %li.btn= link_to 'Develop this App', @app.develop_app_url
      %br
      %ul.buttons
        - if is_admin?
          %li.btn= link_to 'Edit this app', edit_app_path
          %li.btn= link_to 'Delete this app', @app, method: :delete, confirm: 'Are you sure?'