config/routes.rb
DplaPortal::Application.routes.draw do
  resources :apps


  devise_for :users, controllers: {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions      => "sessions",
    :passwords     => "passwords"
  }

  get '/item/:id', to: 'items#show', as: 'item', format: 'html'
  get '/item/:id.json', to: 'items#show', as: 'item_json', format: 'json'
  post '/items/next'
  post '/items/previous'

  resources :subjects, only: :index
  resources :partners, only: :index

  scope only: :show do
    resource :search,    controller: :search
    resource :timeline,  controller: :timeline
    resource :map,       controller: :map
    resource :bookshelf, controller: :bookshelf
  end

  scope '/saved' do
    resources :saved_searches, path: 'searches', only: [:index, :create, :destroy] do
      post 'destroy_bulk', on: :collection
    end
    resources :saved_lists, path: 'lists', id: /\d+/ do
      get 'unlisted', action: :show, on: :collection
    end
    scope '/lists' do
      post   'add_item',              to: 'saved_lists#add_item',          as: :add_saved_item
      delete 'delete_item',           to: 'saved_lists#delete_item',       as: :delete_saved_item
      delete 'delete_positions',      to: 'saved_lists#delete_positions',  as: :delete_positions
      post   'reorder_positions',     to: 'saved_lists#reorder_positions', as: :reorder_positions
      post   'copy_positions',        to: 'saved_lists#copy_positions',    as: :copy_positions
      post   'move_positions',        to: 'saved_lists#move_positions',    as: :move_positions
      post   'switch_status',         to: 'saved_lists#switch_status',     as: :switch_list_status
    end
  end

  match '/welcome' => 'users#welcome'
  root to: 'pages#home'

  # Redner 404 error page for uncatched routes
  match '*a', :to => 'application#render_404', format: false
end

app/models/saved_list.rb
class SavedList < ActiveRecord::Base
  attr_accessible :title, :description, :private

  has_many :saved_items, through: :saved_item_positions
  has_many :saved_item_positions, dependent: :destroy
  belongs_to :user

  validates :title, :user, presence: true

  default_scope order('title ASC')
end

app/controllers/saved_lists_controller.rb
class SavedListsController < ApplicationController
  before_filter :authenticate_user!, except: :show
  before_filter :load_list,  only: [:show, :edit, :update, :destroy, :add_item]
  before_filter :load_lists, only: [:show, :index]
  before_filter :load_saved_item, only: :add_item
  before_filter :prepare_positions_params, only: [:delete_positions, :reorder_positions, :copy_positions, :move_positions]

  def index
    @saved_item_positions = current_user.saved_item_positions
      .includes(:saved_list, :saved_item)
      .select('DISTINCT ON (saved_item_id) *')
      .page(params[:page]).per(20)
    if params[:q].present?
      @searched_item_positions = current_user.saved_item_positions
        .includes(:saved_item)
        .select('DISTINCT ON (saved_item_id) *')
      api_items = get_api_items(@searched_item_positions, params[:q])
      @searched_item_positions.reject! {|x| !api_items[x.saved_item.item_id]}
      @count = @searched_item_positions.size
      @saved_item_positions = @saved_item_positions.where('id in (?)', @searched_item_positions.map { |i| i.id })
    end
    @saved_item_positions = attach_api_items(@saved_item_positions)
  end

  def show
    if @list && (user_signed_in? || !@list.private)
      @saved_item_positions = @list.saved_item_positions
        .includes(:saved_item)
        .order('position ASC')
        .page(params[:page]).per(20)
    elsif user_signed_in?
      @saved_item_positions = @unlisted.page(params[:page]).per(20)
    else
      redirect_to :new_user_session, flash: { error: 'This list is private' }
      return
    end
    attach_api_items @saved_item_positions
  end

  def new
    @list = SavedList.new
  end

  def create
    @list = current_user.saved_lists.new params[:saved_list]
    if @list.save
      redirect_to saved_lists_path
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @list.update_attributes(params[:saved_list])
        format.html { redirect_to @list }
      else
        format.html { render :edit }
      end
        format.json { render :json => @list.private? }
    end
  end

  def destroy
    @list.destroy
    redirect_to saved_lists_path
  end

  def add_item
    current_user
      .saved_item_positions
      .where(saved_item_id: @item, saved_list_id: @list).first_or_create
    redirect_to :back
  end

  def delete_item
    @item_positions = current_user
      .saved_item_positions
      .where saved_item_id: params[:item_id]
    if params[:id].present?
      @item_positions = @item_positions
        .where saved_list_id: params[:id].to_i.nonzero? ? params[:id] : nil
    end
    @item_positions.delete_all
    redirect_to saved_lists_path
  end

  def delete_positions
    @positions.each do |pos|
      if pos[:item]
        current_user.saved_item_positions
          .where(saved_item_id: pos[:item])
          .delete_all
      elsif pos[:position]
        current_user.saved_item_positions
          .where(id: pos[:position])
          .delete_all
      end
    end
    render json: @positions
  end

  def reorder_positions
    @positions.each do |pos|
      position = current_user.saved_item_positions
        .where(id: pos[:position]).first
      position.update_attribute(:position, pos[:value]) if position
    end
    render json: @positions
  end

  def copy_positions
    copy_or_move_position(:copy)
  end

  def move_positions
    copy_or_move_position(:move)
  end

  def switch_status
    target_list = current_user.saved_lists.find params[:list]
    target_list.update_attribute(:private, !target_list.private) if target_list
    redirect_to :back
  end

  private

    def copy_or_move_position(flag)
      @positions.each do |pos|
        target_list = current_user.saved_lists.find params[:list] rescue nil
        next unless target_list

        original_position = current_user.saved_item_positions.find pos[:position] rescue nil
        next unless original_position

        is_duplicate = current_user.saved_item_positions
          .where(saved_item_id: original_position.saved_item, saved_list_id: target_list).present?
        next if is_duplicate

        current_user.saved_item_positions.create(
          saved_list: target_list,
          saved_item: original_position.saved_item
        )
        if (flag == :move)
          current_user.saved_item_positions
            .where(saved_item_id: original_position.saved_item, saved_list_id: original_position.saved_list)
            .delete_all
        end
      end
      render json: @positions
    end

    def load_list
      @is_my_list = true
      if params[:id].present?
        @list = current_user.saved_lists.find params[:id] rescue nil
        if @list.nil?
          @is_my_list = false
          @list = SavedList.find(params[:id]) rescue nil
        end
        render_404 unless @list
      end
    end

    def load_lists
      if user_signed_in?
        @lists = current_user.saved_lists
        @unlisted = current_user.saved_item_positions
          .includes(:saved_item)
          .where('saved_list_id' => nil)
      end
    end

    def load_saved_item
      unless params[:item_id].present?
        redirect_to saved_lists_path
      end
      unless @item = SavedItem.find_by_item_id(params[:item_id])
        if DPLA::Items.by_ids(params[:item_id]).present?
          @item = SavedItem.create item_id: params[:item_id]
        else
          redirect_to saved_lists_path
        end
      end
    end

    def attach_api_items(saved_items_positions)
      api_items = get_api_items(saved_items_positions, nil)
      saved_items_positions.each do |position|
        api_item_id = position.saved_item.item_id
        position.item = api_items[api_item_id] || Item.new('id' => api_item_id)
      end
      saved_items_positions
    end

    def get_api_items(saved_items_positions, search_param)
      api_items = {}.tap do |hash|
        saved_items_positions.each_slice(50) do |slice| 
          conditions = {:q => search_param, :page_size => '50'}
          DPLA::Items.by_ids(slice.map { |p| p.saved_item.item_id }, conditions)
            .each { |item| hash[item.id] = item } rescue nil
        end
      end
    end

    def prepare_positions_params
      @positions = params[:positions] ? params[:positions].map { |k,v| v } : []
    end
end

app/helpers/saved_lists_helper.rb
module SavedListsHelper
  def sort_icon_class
    case params[:sort].to_s.downcase
    when 'asc'  then 'icon-arrow-up'
    when 'desc' then 'icon-arrow-down'
    end
  end

  def sort_link_href
    case params[:sort].to_s.downcase
    when 'asc'  then url_for params.merge(sort: 'desc')
    else url_for params.merge(sort: 'asc')
    end
  end
end

app/views/saved_lists/_aside.html.haml
.leftSide
  .module.itemList.yellow
    %ul.itemList-top
      %li{class: 'index' == params[:action] ? 'active' : ''}
        = link_to 'All Items', saved_lists_path, class: 'name'
    %h4 Your Lists
    %ul
      - unlisted_active = 'show' == params[:action] && @list.blank?
      %li{class: unlisted_active ? 'active' : ''}
        %span.name
          = link_to 'Your Saved Items', unlisted_saved_lists_path
          %span.icon-lock{'aria-hidden' => true}
        %span= @unlisted.count
      - @lists.each do |list|
        %li{class: list.eql?(@list) ? 'active ' + list.id.to_s : ''}
          - locked = list.private? ? 'icon-lock' : 'icon-unlocked'
          %span.name
            = link_to list.title, list
            %span
              - list_data = {list: list.id}
            %span{class: "statusLink #{locked}", data: list_data, title: list.private? ? 'Set public status' : 'Set private status'}
          %span= list.saved_items.count
          = link_to 'edit', edit_saved_list_path(list), class: :edit
          = link_to '×',    list, class: :remove, method: :delete, confirm: 'Are you sure?'
    = link_to 'Add New', new_saved_list_path, class: :btn
  .div.search-module
    = form_tag(saved_lists_path, method: :get, class: "search-form") do
      = text_field_tag :q, params[:q], placeholder: 'Search the Library'
      = submit_tag 'Search', class: 'searchBtn', name: nil

app/views/saved_lists/_form.html.haml
= simple_form_for @list do |f|
  = f.input :title
  .textarea
    = f.input :description, as: :text, input_html: { rows: 10 }
  .checkbox
    = f.input :private,     as: :boolean
  %br
  %a.btn{:href => ""} Save

app/views/saved_lists/_list.html.haml
.list-detail
  - if @list.present?
    %h2{class: @list.private? ? 'private' : ''}
      = @list.title
      - locked = @list.private? ? 'icon-lock' : 'icon-unlocked'
      %span#selectedListStatus
        %span{class: "#{locked}", 'aria-hidden' => true}
          Private
    - if @list.description.present?
      %p= @list.description
  - else
    %h2{class: 'private'}
      Your Saved Items
      %span
        %span.icon-lock{'aria-hidden' => true}
        Private
- if @saved_item_positions.present?
  = render partial: 'paginator'
  .savedList
    %form
      %section
        -if @is_my_list
          = check_box_tag nil, nil, nil, class: 'checkbox select-all'
        .searchLeft
        .searchMiddle
        -if @is_my_list
          .searchRight
            %h5 Order
          .delete
            %h5 Remove
      - @saved_item_positions.each do |position|
        - saved_item = position.saved_item
        %section
          -if @is_my_list
            - checkbox_data = { position: position.id, list: @list ? @list.id : 'unlisted' }
            = check_box_tag :position, nil, nil, id: nil, class: 'checkbox item', data: checkbox_data
          .searchLeft
            %h4= link_to position.item.title, item_path(position.item.id)
            %p= position.item.description
            = view_object_link(position.item)
          .searchMiddle
            = item_thumbnail(position.item, request)
          -if @is_my_list
            .searchRight
              - position_value = position.position.to_i.zero? ? nil : position.position
              = text_field_tag :position, position_value, placeholder: 0, id: nil, class: 'position item', data: {position: position.id}
            .delete
              - delete_path = delete_saved_item_path(item_id: saved_item, id: @list || 'unlisted')
              = link_to '×', delete_path, class: :remove, method: :delete, confirm: 'Are you sure?'
- else
  %p Empty list
- if @saved_item_positions.present?
  // TODO: I'm very sorry for this dirty passing params, but locals: {is_bottom: true}
  // absolutely doesn't work. Very strange, may by is's bug in Rails.
  // I'll come back to this problem later
  - @is_bottom = true
  = render partial: 'paginator'

app/views/saved_lists/_paginator.html.haml
- is_list = 'show'  == params[:action]
-if @is_my_list || current_page?(action: 'index')
  .resultsBar{id: @is_bottom ? 'resultsBarBottom' : 'resultsBarTop'}
    %ul
      - if is_list
        - lists = @lists - [@list]
        - if lists.present?
          %li{id: :copy_items_to}
            = link_to @list, class: :btn do
              = 'Copy to...'
              %span{'aria-hidden' => true, class: @is_bottom ? 'icon-arrow-up' : 'icon-arrow-down'}
            %ul
              - lists.each do |list|
                %li
                  = link_to list.title, list, data: {list: list.id}
      - else
        - if @lists.present?
          %li{id: :move_items_to}
            = link_to @list, class: :btn do
              = 'Add to...'
              %span{'aria-hidden' => true, class: @is_bottom ? 'icon-arrow-up' : 'icon-arrow-down'}
            %ul
              - @lists.each do |list|
                %li
                  = link_to list.title, list, data: {list: list.id}
      %li
        = link_to 'Remove', @list, class: 'btn remove_items'
      - if is_list
        %li
          = link_to 'Reorder', @list, class: 'btn reorder_items'


  .pagination.drop= paginate @saved_item_positions

app/views/saved_lists/edit.html.haml
- page_title! t('.title', title: @list.title_was)

.layout.fullWidth
  = render 'shared/search_panel'

  %article#content{role: "main"}
    %h1 Your Profile
    .profile
      = render partial: 'shared/profile/tabs'
      .tab-content
        %h1
          Edit Saved List
          = "&laquo;#{@list.title_was}&raquo;".html_safe
        .account
          = render partial: 'form'

app/views/saved_lists/index.html.haml
.layout.fullWidth
  = render 'shared/search_panel'
  %article#content{role: "main"}
    %h1 Your Profile
    .profile
      = render partial: 'shared/profile/tabs'
      .tab-content
        = render partial: 'aside'
        .rightSide
          .list-detail
            - if params[:q].present?
              %h4
                -if @saved_item_positions.nil?
                  Your search for
                  %span= params[:q]
                  returned no results.
                -else
                  Your search for
                  %span= params[:q]
                  returned
                  = number_with_delimiter @count, delimiter: ','
                  results.
            - else
              %h2 All Items
          - if @saved_item_positions.present?
            = render partial: 'paginator'
            .savedList
              %form
                %section
                = check_box_tag nil, nil, nil, class: 'checkbox select-all'
                .searchLeft
                .searchMiddle
                .searchRight
                  %h5 List
                .delete
                  %h5 Remove
                - @saved_item_positions.each do |position|
                  - saved_item = position.saved_item
                  %section
                    - checkbox_data = {item: saved_item.id, position: position.id}
                    = check_box_tag :item, nil, nil, id: nil, class: 'checkbox item', data: checkbox_data
                    .searchLeft
                      %h4= link_to position.item.title, item_path(position.item.id)
                      %p= position.item.description
                      = view_object_link(position.item)
                    .searchMiddle
                      = item_thumbnail(position.item, request)
                    .searchRight
                      - #lists = saved_item.saved_item_positions.includes(:saved_list).map { |p| p.saved_list }
                      - lists = position.neighbors.map { |p| p.saved_list }
                      - lists.each do |list|
                        %span
                          - if list.present?
                            = link_to list.title, list
                          - else
                            = link_to 'Your Saved Items', unlisted_saved_lists_path

                    .delete
                      - delete_path = delete_saved_item_path(item_id: saved_item.id)
                      = link_to '×', delete_path, class: :remove, method: :delete, confirm: 'Are you sure?'
          - else
            %p Empty list
          - if @saved_item_positions.present?
            // TODO: I'm very sorry for this dirty passing params, but locals: {is_bottom: true}
            // absolutely doesn't work. Very strange, may by is's bug in Rails.
            // I'll come back to this problem later
            - @is_bottom = true
            = render partial: 'paginator'

app/views/saved_lists/new.html.haml
.layout.fullWidth
  = render 'shared/search_panel'

  %article#content{role: "main"}
    %h1 Your Profile
    .profile
      = render partial: 'shared/profile/tabs'
      .tab-content
        %h1 New Saved List
        .account
          = render partial: 'form'

app/views/saved_lists/show.html.haml
- if @list.present?
  - page_title! t('.title', title: @list.title)
- else
  - page_title! t('.title_unlisted')

.layout.fullWidth
-if @is_my_list
  = render 'shared/search_panel'
  %article#content{role: "main"}
    %h1 Your Profile
    .profile
      = render partial: 'shared/profile/tabs'
      .tab-content
        = render partial: 'aside'
        .rightSide
          = render partial: 'list'
-elsif @list.private
  = render 'shared/search_panel'
  %article#content{role: "main"}
    This list is private.
-else
  = render 'shared/search_panel'
  %article#content{role: "main"}
    .profile
      .tab-content
        = render partial: 'list'